wip: fetch field translations
OpenFn/primero-thailand pull request #32
Opened 2022-09-07 15:22 UTC by mtuchi

#### Description
- [x] Query `/forms`
- [x] Search for select fields using `data[*].fields[*].name` path
- [x] Throw error when field not found
- [x] Remove word `lookup` in option_strings_source before save to var optionStringsSourceLookupName
- [ ] Store `option_strings_text` for field without `option_strings_source`

#### Testing
For testing add this in your `state.json`
```
"fields_references": [
        "location_current",
        "occupation_1",
        "if_out_of_school__specify_reason",
        "nationality_fa822dc",
        "gender_4e8704a",
        "relationship_with_the_abused_eb757fc",
        "social_status_6c1074a",
        "occupation_09639f9",
        "stimulant_9191303",
        "relation_within_family_41a62f4",
        "environment_3c4fc2b",
        "economic_issues_84c5b46",
        "physical_issue_1f182e4",
        "mental_issue_5607d21",
        "relationship_with_the_abused_365fcd1",
        "gender_2dea3c9",
        "social_status_7c0989a",
        "occupation_c4d6420",
        "location_of_the_incident_885fe8c",
        "sender_s_gender_b83c931",
        "sender_s_occupation_3ed671e",
        "type_of_place_where_the_incident_occurred_bdc967d",
        "type_of_abuse_431f2ba",
        "specify_physical_abuse_4867f38",
        "specify_sexual_abuse_16d36f7",
        "specify_physical_interaction_d13d273",
        "sexual_intercourse_a1585d0",
        "if_no_physical_touch__please_specify_1159dde",
        "specify_mental_abuse_6182644",
        "specify_neglect_9b8a22b",
        "specify_exploitation_ef65c2e",
        "specify_human_trafficking_dca84dd",
        "stimulant_a4096c2",
        "relation_within_family_a6c45fd",
        "economic_issue_a445217",
        "physical_issue_2e9f1c6",
        "mental_issue_4785ece",
        "urgent_protection_concern",
        "risk_level",
        "social_problems_identified_1",
        "home_visit_required__2",
        "vagina_details",
        "cervix_details",
        "discharge_details",
        "uterus_details",
        "penis_details_79f31be",
        "urethra_and_discharge_60eb64e",
        "scrotal_sac_f93e04a",
        "anus_and_rectum_eaf3784",
        "source_of_information_44cac9a",
        "disabilities_1",
        "chronic_illness",
        "mental_illness",
        "behavior_of_risk",
        "developmental_issue",
        "vaccinations_are_up_to_date",
        "nutritional_conditions_are_adequate",
        "caregiver_s_disabilities",
        "caregiver_s_chronic_illness_es",
        "caregiver_s_mental_illness_es",
        "caregiver_s_economic_issue_s",
        "caregiver_s_substance_abuse_issue",
        "physical_abuse_issue",
        "gambling_issue_in_the_family",
        "substance_abuse_in_the_family_community",
        "entertainment_venues_near_the_household",
        "girls_lie_together_in_the_same_room_as_their_male_relatives",
        "girls_lie_together_in_the_same_room_as_their_female_relatives",
        "boys_lie_in_the_same_room_as_their_female_relatives",
        "boys_lie_together_in_the_same_room_as_their_male_relatives",
        "history_of_illegal_activities_behaviors_in_the_family",
        "history_of_child_labor_in_the_family_community",
        "bullying",
        "mingling_and_causing_annoyance_to_others",
        "gambling",
        "substance_abuse",
        "involved_in_sex_trade",
        "behaves_in_a_sexually_inappropriate_or_obscene_manner",
        "resisting_parental_teachings",
        "family_status",
        "is_this_person_living_in_the_same_household_as_patient_7d39e1d",
        "relation",
        "relation_is_alive",
        "relation_nationality",
        "occupation_3",
        "relation_location_current",
        "reason_for_unexpected_pregnancy",
        "specify_contraception_problem",
        "specify_legal_offenses",
        "factors_for_pregnancy_termination",
        "specify_physical_issue",
        "specify_mental_issue",
        "specify_family_social_economic_issues",
        "patient_provided_with_alternative_counseling",
        "patient_decision_after_being_provided_with_alternative_counseling",
        "antenatal_care_will_be_provided_at",
        "support_needed",
        "support_needed_1",
        "source_of_information_647b9db",
        "is_the_subject_given_the_benefit_of_the_doubt_",
        "assessment_method",
        "urgent_protection_concern",
        "protection_concerns",
        "risk_level",
        "conference_type",
        "conference_reason",
        "conference_case_status",
        "conference_case_transfer_reason",
        "relation_to_the_child_37c30dc",
        "protection_concerns",
        "sex_check_and_evaluation",
        "physical",
        "mental",
        "social",
        "physical_1",
        "mental_1",
        "reproductive_health",
        "psycho_social",
        "status_of_treatment_plan_a8ca0e8",
        "service_response_type",
        "service_type",
        "service_response_timeframe",
        "service_implementing_agency",
        "service_implementing_agency_individual",
        "service_referral",
        "service_implemented",
        "service_delivery_location",
        "status_of_treatment_plan_a8ca0e8",
        "protection_concerns",
        "risk_level",
        "followup_type",
        "child_was_seen",
        "reason_child_not_seen",
        "action_taken_already",
        "need_follow_up_visit",
        "recommend_case_closed",
        "status",
        "closure_reason"
    ],
```

2022-09-07 15:27 UTC, taylordowns2000 requested changes
looking good, @mtuchi , but we're pushing people towards multiple operations these days. can you adjust this and add comments:
```js
// get forms from Primero
get();

// pluck out option strings sources
fn(state => {
  ...blah
});
```

2022-09-08 20:48 UTC, mtuchi commented
**Find the `lookup` name for each field via the `/forms` endpoint...**

- [x] 1. Query `https://demo-care-thai-kids.primero.org/api/v2/forms/` using the credential listed in `state.json` below 
- [x] 2. In the response, search for all 139 fields listed in the **select fields tab** of the [mapping specifications document](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?pli=1#gid=954677598). Search for the fields using this path: `data[*].fields[*].name`
- [x] 3. If a field is not found in the response, throw error with message `field ${fieldName} not found`
- [x] 4. For each field that is found, find the value stored in key `option_strings_source`. These values will be used in the following steps. (Remove the first "lookup" before saving it in a variable `optionStringsSourceLookupName`). Ex. if `"option_strings_source" = "lookup lookup-yes-no-unknown"`, capture `lookup-yes-no-unknown` for later use. 

**Find the option value ids & translations via the `/lookups` endpoint...**

- [x] 6. Query `https://demo-care-thai-kids.primero.org/api/v2/lookups?per=1000000&page=1` using the credential below. This should return ALL available lookup records in 1 page.  
- [x] 7.  The response will return an array of records (`data[*]`). Search the array for all of the `option_strings_source` values stored in step 4, looking for the object `data[*].unique_id` where `unique_id === ${optionStringsSourceLookupName}`
- [x] 8. If lookup not found throw error and log message  `Options not found for lookup ${optionStringsSourceLookupName}`

**Generate a map of option value ids and translations...**

- [x] 10. For each `optionStringsSourceLookupName`, generate a table which maps `data.values[*].id` to  `data.values[*].display_text.th` for each item in values. 
- [ ] 11. Post the resulting JSON object to the OpenFn Project Inbox as a `Message` that we can inspect to ensure the correct output was generated. 

- [x] **Desired mapping output**:

```
{
"lookup-yes-no-unknown": { 
     "true": "ใช่", 
     "false": "ไม่ใช่",
     "unknown": "ไม่ทราบ"
   },
 "conference_case_transfer_reason":  { 
     "specialized_service": "ต้องการการบริการพิเศษ",
     "new_location": "ย้ายสถานที่อยู่ใหม่"
     "organisational_reasons": "เหตุผลของหน่วยงาน"
   }
}
```

@taylordowns2000 this is the progress so far, hoping to finish task `11` tomorrow

2022-09-09 11:50 UTC, mtuchi commented
@taylordowns2000 this is ready for review,
 Quick heads up  you need to update your `state.json` to have Google `googleApiKey` and `spreedsheetId` for this to work, Since i am pulling `SELECT FIELDS` from Google Spreedsheet
```
{
  "configuration": {
      "url": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "user": "SEE LP for `Primero Thailand Demo API User (Open Function)`", 
     "password": "SEE LP for `Primero Thailand Demo API User (Open Function)`",
     "basicAuth": true,
     "openFnInboxURL": "Copy it from this page https://www.openfn.org/projects/primero-thailand-io-unicef---staging/settings",
     "googleApiKey": "SEE -> https://console.cloud.google.com/apis/api/sheets.googleapis.com/overview?",
     "spreedsheetUrl": "https://sheets.googleapis.com/v4/spreadsheets",
     "spreedsheetId": "SEE -> https://stackoverflow.com/questions/36061433/how-to-do-i-locate-a-google-spreadsheet-id"
  },
  "data": {}
}
```

cc @aleksa-krolls @daissatou2

2022-09-09 16:36 UTC, taylordowns2000 approved these changes

2022-09-09 16:36 UTC, taylordowns2000 approved these changes

2022-09-09 16:36 UTC, merged